//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.01 at 10:46:05 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = GenericCFD.CFD_3_NAMESPACE, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.infra.factura.business.cfdi.addenda.schema;
import com.infra.factura.business.common.GenericCFD;

