package com.infra.factura.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-29T11:57:05.367-05:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IConsultaCFDIService")
@XmlSeeAlso({ObjectFactory.class})
public interface IConsultaCFDIService {

    @WebResult(name = "ConsultaResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IConsultaCFDIService/Consulta", output = "http://tempuri.org/IConsultaCFDIService/ConsultaResponse")
    @RequestWrapper(localName = "Consulta", targetNamespace = "http://tempuri.org/", className = "com.infra.factura.ws.Consulta")
    @WebMethod(operationName = "Consulta", action = "http://tempuri.org/IConsultaCFDIService/Consulta")
    @ResponseWrapper(localName = "ConsultaResponse", targetNamespace = "http://tempuri.org/", className = "com.infra.factura.ws.ConsultaResponse")
    public com.infra.factura.ws.Acuse consulta(
        @WebParam(name = "expresionImpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String expresionImpresa
    );
}
