//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 04:55:55 PM CST 
//


package com.infra.factura.business.cfdi.addenda.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sfe.business.cfdi.addenda.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddendaRequestForPaymentSpecialInstructionText_QNAME = new QName("", "text");
    private final static QName _AddendaRequestForPaymentShipToNameAndAddressPostalCode_QNAME = new QName("", "postalCode");
    private final static QName _AddendaRequestForPaymentShipToNameAndAddressStreetAddressOne_QNAME = new QName("", "streetAddressOne");
    private final static QName _AddendaRequestForPaymentShipToNameAndAddressName_QNAME = new QName("", "name");
    private final static QName _AddendaRequestForPaymentShipToNameAndAddressCity_QNAME = new QName("", "city");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sfe.business.cfdi.addenda.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Addenda }
     * 
     */
    public Addenda createAddenda() {
        return new Addenda();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment }
     * 
     */
    public Addenda.RequestForPayment createAddendaRequestForPayment() {
        return new Addenda.RequestForPayment();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem }
     * 
     */
    public Addenda.RequestForPayment.LineItem createAddendaRequestForPaymentLineItem() {
        return new Addenda.RequestForPayment.LineItem();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TotalLineAmount }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TotalLineAmount createAddendaRequestForPaymentLineItemTotalLineAmount() {
        return new Addenda.RequestForPayment.LineItem.TotalLineAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TradeItemTaxInformation }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TradeItemTaxInformation createAddendaRequestForPaymentLineItemTradeItemTaxInformation() {
        return new Addenda.RequestForPayment.LineItem.TradeItemTaxInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AllowanceCharge }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AllowanceCharge createAddendaRequestForPaymentLineItemAllowanceCharge() {
        return new Addenda.RequestForPayment.LineItem.AllowanceCharge();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage createAddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentage() {
        return new Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.ExtendedAttributes }
     * 
     */
    public Addenda.RequestForPayment.LineItem.ExtendedAttributes createAddendaRequestForPaymentLineItemExtendedAttributes() {
        return new Addenda.RequestForPayment.LineItem.ExtendedAttributes();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.PalletInformation }
     * 
     */
    public Addenda.RequestForPayment.LineItem.PalletInformation createAddendaRequestForPaymentLineItemPalletInformation() {
        return new Addenda.RequestForPayment.LineItem.PalletInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.LogisticUnits }
     * 
     */
    public Addenda.RequestForPayment.LineItem.LogisticUnits createAddendaRequestForPaymentLineItemLogisticUnits() {
        return new Addenda.RequestForPayment.LineItem.LogisticUnits();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.Customs }
     * 
     */
    public Addenda.RequestForPayment.LineItem.Customs createAddendaRequestForPaymentLineItemCustoms() {
        return new Addenda.RequestForPayment.LineItem.Customs();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AdditionalInformation }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AdditionalInformation createAddendaRequestForPaymentLineItemAdditionalInformation() {
        return new Addenda.RequestForPayment.LineItem.AdditionalInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.AllowanceCharge }
     * 
     */
    public Addenda.RequestForPayment.AllowanceCharge createAddendaRequestForPaymentAllowanceCharge() {
        return new Addenda.RequestForPayment.AllowanceCharge();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage }
     * 
     */
    public Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage createAddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentage() {
        return new Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PaymentTerms }
     * 
     */
    public Addenda.RequestForPayment.PaymentTerms createAddendaRequestForPaymentPaymentTerms() {
        return new Addenda.RequestForPayment.PaymentTerms();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PaymentTerms.NetPayment }
     * 
     */
    public Addenda.RequestForPayment.PaymentTerms.NetPayment createAddendaRequestForPaymentPaymentTermsNetPayment() {
        return new Addenda.RequestForPayment.PaymentTerms.NetPayment();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod }
     * 
     */
    public Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod createAddendaRequestForPaymentPaymentTermsNetPaymentPaymentTimePeriod() {
        return new Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Customs }
     * 
     */
    public Addenda.RequestForPayment.Customs createAddendaRequestForPaymentCustoms() {
        return new Addenda.RequestForPayment.Customs();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.InvoiceCreator }
     * 
     */
    public Addenda.RequestForPayment.InvoiceCreator createAddendaRequestForPaymentInvoiceCreator() {
        return new Addenda.RequestForPayment.InvoiceCreator();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.ShipTo }
     * 
     */
    public Addenda.RequestForPayment.ShipTo createAddendaRequestForPaymentShipTo() {
        return new Addenda.RequestForPayment.ShipTo();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Seller }
     * 
     */
    public Addenda.RequestForPayment.Seller createAddendaRequestForPaymentSeller() {
        return new Addenda.RequestForPayment.Seller();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Buyer }
     * 
     */
    public Addenda.RequestForPayment.Buyer createAddendaRequestForPaymentBuyer() {
        return new Addenda.RequestForPayment.Buyer();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Buyer.ContactInformation }
     * 
     */
    public Addenda.RequestForPayment.Buyer.ContactInformation createAddendaRequestForPaymentBuyerContactInformation() {
        return new Addenda.RequestForPayment.Buyer.ContactInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.AdditionalInformation }
     * 
     */
    public Addenda.RequestForPayment.AdditionalInformation createAddendaRequestForPaymentAdditionalInformation() {
        return new Addenda.RequestForPayment.AdditionalInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.OrderIdentification }
     * 
     */
    public Addenda.RequestForPayment.OrderIdentification createAddendaRequestForPaymentOrderIdentification() {
        return new Addenda.RequestForPayment.OrderIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.RequestForPaymentIdentification }
     * 
     */
    public Addenda.RequestForPayment.RequestForPaymentIdentification createAddendaRequestForPaymentRequestForPaymentIdentification() {
        return new Addenda.RequestForPayment.RequestForPaymentIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.SpecialInstruction }
     * 
     */
    public Addenda.RequestForPayment.SpecialInstruction createAddendaRequestForPaymentSpecialInstruction() {
        return new Addenda.RequestForPayment.SpecialInstruction();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.DeliveryNote }
     * 
     */
    public Addenda.RequestForPayment.DeliveryNote createAddendaRequestForPaymentDeliveryNote() {
        return new Addenda.RequestForPayment.DeliveryNote();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Currency }
     * 
     */
    public Addenda.RequestForPayment.Currency createAddendaRequestForPaymentCurrency() {
        return new Addenda.RequestForPayment.Currency();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.TotalAmount }
     * 
     */
    public Addenda.RequestForPayment.TotalAmount createAddendaRequestForPaymentTotalAmount() {
        return new Addenda.RequestForPayment.TotalAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.TotalAllowanceCharge }
     * 
     */
    public Addenda.RequestForPayment.TotalAllowanceCharge createAddendaRequestForPaymentTotalAllowanceCharge() {
        return new Addenda.RequestForPayment.TotalAllowanceCharge();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.BaseAmount }
     * 
     */
    public Addenda.RequestForPayment.BaseAmount createAddendaRequestForPaymentBaseAmount() {
        return new Addenda.RequestForPayment.BaseAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Tax }
     * 
     */
    public Addenda.RequestForPayment.Tax createAddendaRequestForPaymentTax() {
        return new Addenda.RequestForPayment.Tax();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PayableAmount }
     * 
     */
    public Addenda.RequestForPayment.PayableAmount createAddendaRequestForPaymentPayableAmount() {
        return new Addenda.RequestForPayment.PayableAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TradeItemIdentification }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TradeItemIdentification createAddendaRequestForPaymentLineItemTradeItemIdentification() {
        return new Addenda.RequestForPayment.LineItem.TradeItemIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification createAddendaRequestForPaymentLineItemAlternateTradeItemIdentification() {
        return new Addenda.RequestForPayment.LineItem.AlternateTradeItemIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation createAddendaRequestForPaymentLineItemTradeItemDescriptionInformation() {
        return new Addenda.RequestForPayment.LineItem.TradeItemDescriptionInformation();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.InvoicedQuantity }
     * 
     */
    public Addenda.RequestForPayment.LineItem.InvoicedQuantity createAddendaRequestForPaymentLineItemInvoicedQuantity() {
        return new Addenda.RequestForPayment.LineItem.InvoicedQuantity();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AditionalQuantity }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AditionalQuantity createAddendaRequestForPaymentLineItemAditionalQuantity() {
        return new Addenda.RequestForPayment.LineItem.AditionalQuantity();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.GrossPrice }
     * 
     */
    public Addenda.RequestForPayment.LineItem.GrossPrice createAddendaRequestForPaymentLineItemGrossPrice() {
        return new Addenda.RequestForPayment.LineItem.GrossPrice();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.NetPrice }
     * 
     */
    public Addenda.RequestForPayment.LineItem.NetPrice createAddendaRequestForPaymentLineItemNetPrice() {
        return new Addenda.RequestForPayment.LineItem.NetPrice();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount createAddendaRequestForPaymentLineItemTotalLineAmountGrossAmount() {
        return new Addenda.RequestForPayment.LineItem.TotalLineAmount.GrossAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount createAddendaRequestForPaymentLineItemTotalLineAmountNetAmount() {
        return new Addenda.RequestForPayment.LineItem.TotalLineAmount.NetAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount }
     * 
     */
    public Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount createAddendaRequestForPaymentLineItemTradeItemTaxInformationTradeItemTaxAmount() {
        return new Addenda.RequestForPayment.LineItem.TradeItemTaxInformation.TradeItemTaxAmount();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit createAddendaRequestForPaymentLineItemAllowanceChargeMonetaryAmountOrPercentageRatePerUnit() {
        return new Addenda.RequestForPayment.LineItem.AllowanceCharge.MonetaryAmountOrPercentage.RatePerUnit();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber }
     * 
     */
    public Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber createAddendaRequestForPaymentLineItemExtendedAttributesLotNumber() {
        return new Addenda.RequestForPayment.LineItem.ExtendedAttributes.LotNumber();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.PalletInformation.Description }
     * 
     */
    public Addenda.RequestForPayment.LineItem.PalletInformation.Description createAddendaRequestForPaymentLineItemPalletInformationDescription() {
        return new Addenda.RequestForPayment.LineItem.PalletInformation.Description();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.PalletInformation.Transport }
     * 
     */
    public Addenda.RequestForPayment.LineItem.PalletInformation.Transport createAddendaRequestForPaymentLineItemPalletInformationTransport() {
        return new Addenda.RequestForPayment.LineItem.PalletInformation.Transport();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode }
     * 
     */
    public Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode createAddendaRequestForPaymentLineItemLogisticUnitsSerialShippingContainerCode() {
        return new Addenda.RequestForPayment.LineItem.LogisticUnits.SerialShippingContainerCode();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification }
     * 
     */
    public Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification createAddendaRequestForPaymentLineItemCustomsAlternatePartyIdentification() {
        return new Addenda.RequestForPayment.LineItem.Customs.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.Customs.NameAndAddress }
     * 
     */
    public Addenda.RequestForPayment.LineItem.Customs.NameAndAddress createAddendaRequestForPaymentLineItemCustomsNameAndAddress() {
        return new Addenda.RequestForPayment.LineItem.Customs.NameAndAddress();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification }
     * 
     */
    public Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification createAddendaRequestForPaymentLineItemAdditionalInformationReferenceIdentification() {
        return new Addenda.RequestForPayment.LineItem.AdditionalInformation.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate }
     * 
     */
    public Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate createAddendaRequestForPaymentAllowanceChargeMonetaryAmountOrPercentageRate() {
        return new Addenda.RequestForPayment.AllowanceCharge.MonetaryAmountOrPercentage.Rate();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PaymentTerms.DiscountPayment }
     * 
     */
    public Addenda.RequestForPayment.PaymentTerms.DiscountPayment createAddendaRequestForPaymentPaymentTermsDiscountPayment() {
        return new Addenda.RequestForPayment.PaymentTerms.DiscountPayment();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue }
     * 
     */
    public Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue createAddendaRequestForPaymentPaymentTermsNetPaymentPaymentTimePeriodTimePeriodDue() {
        return new Addenda.RequestForPayment.PaymentTerms.NetPayment.PaymentTimePeriod.TimePeriodDue();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Customs.AlternatePartyIdentification }
     * 
     */
    public Addenda.RequestForPayment.Customs.AlternatePartyIdentification createAddendaRequestForPaymentCustomsAlternatePartyIdentification() {
        return new Addenda.RequestForPayment.Customs.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Customs.NameAndAddress }
     * 
     */
    public Addenda.RequestForPayment.Customs.NameAndAddress createAddendaRequestForPaymentCustomsNameAndAddress() {
        return new Addenda.RequestForPayment.Customs.NameAndAddress();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification }
     * 
     */
    public Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification createAddendaRequestForPaymentInvoiceCreatorAlternatePartyIdentification() {
        return new Addenda.RequestForPayment.InvoiceCreator.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.InvoiceCreator.NameAndAddress }
     * 
     */
    public Addenda.RequestForPayment.InvoiceCreator.NameAndAddress createAddendaRequestForPaymentInvoiceCreatorNameAndAddress() {
        return new Addenda.RequestForPayment.InvoiceCreator.NameAndAddress();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.ShipTo.NameAndAddress }
     * 
     */
    public Addenda.RequestForPayment.ShipTo.NameAndAddress createAddendaRequestForPaymentShipToNameAndAddress() {
        return new Addenda.RequestForPayment.ShipTo.NameAndAddress();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Seller.AlternatePartyIdentification }
     * 
     */
    public Addenda.RequestForPayment.Seller.AlternatePartyIdentification createAddendaRequestForPaymentSellerAlternatePartyIdentification() {
        return new Addenda.RequestForPayment.Seller.AlternatePartyIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName }
     * 
     */
    public Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName createAddendaRequestForPaymentBuyerContactInformationPersonOrDepartmentName() {
        return new Addenda.RequestForPayment.Buyer.ContactInformation.PersonOrDepartmentName();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification }
     * 
     */
    public Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification createAddendaRequestForPaymentAdditionalInformationReferenceIdentification() {
        return new Addenda.RequestForPayment.AdditionalInformation.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification }
     * 
     */
    public Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification createAddendaRequestForPaymentOrderIdentificationReferenceIdentification() {
        return new Addenda.RequestForPayment.OrderIdentification.ReferenceIdentification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text", scope = Addenda.RequestForPayment.SpecialInstruction.class)
    public JAXBElement<String> createAddendaRequestForPaymentSpecialInstructionText(String value) {
        return new JAXBElement<String>(_AddendaRequestForPaymentSpecialInstructionText_QNAME, String.class, Addenda.RequestForPayment.SpecialInstruction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postalCode", scope = Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createAddendaRequestForPaymentShipToNameAndAddressPostalCode(String value) {
        return new JAXBElement<String>(_AddendaRequestForPaymentShipToNameAndAddressPostalCode_QNAME, String.class, Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "streetAddressOne", scope = Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createAddendaRequestForPaymentShipToNameAndAddressStreetAddressOne(String value) {
        return new JAXBElement<String>(_AddendaRequestForPaymentShipToNameAndAddressStreetAddressOne_QNAME, String.class, Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createAddendaRequestForPaymentShipToNameAndAddressName(String value) {
        return new JAXBElement<String>(_AddendaRequestForPaymentShipToNameAndAddressName_QNAME, String.class, Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city", scope = Addenda.RequestForPayment.ShipTo.NameAndAddress.class)
    public JAXBElement<String> createAddendaRequestForPaymentShipToNameAndAddressCity(String value) {
        return new JAXBElement<String>(_AddendaRequestForPaymentShipToNameAndAddressCity_QNAME, String.class, Addenda.RequestForPayment.ShipTo.NameAndAddress.class, value);
    }

}
