//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.09 at 01:18:23 AM CDT 
//


package com.infra.factura.business.cfd.ii.schema;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, String>
{


    public String unmarshal(String value) {
        return (com.infra.factura.business.schema.util.SATStringDecimalBinder.parseStringDecimal(value));
    }

    public String marshal(String value) {
        return (com.infra.factura.business.schema.util.SATStringDecimalBinder.printStringDecimal(value));
    }

}
